services:
  - type: web
    name: task-app-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    routes:
      - type: rewrite
        source: /
        destination: /index.html